# Generated by Django 3.2.3 on 2021-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210522_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='is_sensor_color',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Sensor de Cor'),
        ),
    ]
