# Generated by Django 3.2.3 on 2021-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sensor_is_sensor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='is_sensor_color',
            field=models.BooleanField(default=True, verbose_name='Sensor de Cor'),
        ),
    ]
