# Generated by Django 3.2.3 on 2021-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sensor_is_sensor_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='industrial',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='is_sensor_color',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_color',
        ),
        migrations.AddField(
            model_name='sensor',
            name='type_sensor',
            field=models.CharField(blank=True, choices=[('C', 'COR'), ('A', 'CORRENTE'), ('V', 'TENSÃO'), ('L', 'NÍVEL'), ('F', 'VAZÃO'), ('T', 'TEMPERATURA')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
