# Generated by Django 3.2.3 on 2021-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210522_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome do Usuário:')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Senha')),
                ('confirmation_password', models.CharField(max_length=20, verbose_name='Confirmação de Senha')),
                ('office', models.CharField(max_length=20, verbose_name='Cargo na Empresa')),
            ],
        ),
    ]
