# Generated by Django 3.2.3 on 2021-05-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userssystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='value',
        ),
        migrations.AlterField(
            model_name='userssystem',
            name='office',
            field=models.CharField(choices=[('T', 'ESTÁGIARIO'), ('S', 'ESPECIALISTA'), ('P', 'PROFICIONAL'), ('J', 'FAXINEIRO'), ('C', 'CONTADOR'), ('W', 'PO'), ('L', 'ADVOGADO'), ('D', 'DESENVOLVEDOR')], default='T', max_length=20, verbose_name='Cargo na Empresa'),
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor')),
            ],
        ),
    ]
