# Generated by Django 3.2.3 on 2021-05-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210522_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values',
            new_name='Value',
        ),
    ]
