# Generated by Django 3.2.3 on 2021-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_sensor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='model',
            field=models.CharField(default='Sensor', max_length=20),
            preserve_default=False,
        ),
    ]
